python3 main_codeSearch.py \
    --output_dir=./ \
    --train_data_file_CodeSearch=./datasets/code_search/train.jsonl \
    --eval_data_file_CodeSearch=./datasets/code_search/valid.jsonl \
    --test_data_file_CodeSearch=./datasets/code_search/test.jsonl \
    --model_name_or_path=Salesforce/codet5-base   \
    --tokenizer_name=Salesforce/codet5-base   \
    --nl_length 128 \
    --code_length 512 \
    --do_optimization True \
    --train_batch_size 32 \
    --eval_batch_size 32 \
    --train_data_rate_code_search 1.0 \
    --learning_rate 1e-4 \
    --population_size 50 \
    --sample_size 10 \
    --nb_samples 10000 \
    --cycles 30 \
    --max_grad_norm 1.0 \
    --num_train_epochs 5 \
    --optimization_history_file=logs_optim/codet5_optim_history_codesearch.txt \
    --stats_file=logs_optim/codet5_stats_codeSearch.json \
    --seed 42 2>&1 | tee ./logs_optim/codet5_codeSearch.log
