python3 main_defect.py \
    --train_data_file_defect=./datasets/dataset_defect/train.jsonl \
    --output_dir=./ \
    --eval_data_file_defect=./datasets/dataset_defect/valid.jsonl \
    --test_data_file_defect=./datasets/dataset_defect/test.jsonl \
    --model_name_or_path=Salesforce/codet5p-220m \
    --tokenizer_name=Salesforce/codet5p-220m \
    --num_classes 1 \
    --nl_length 128 \
    --code_length 512 \
    --do_train True \
    --train_batch_size 32 \
    --eval_batch_size 32 \
    --train_data_rate_defect 1.0 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 15 \
    --seed 42 2>&1 | tee ./baselines/codet5p_defect_prefix.log
