python3 main_flaky.py \
    --train_data_file_flaky=./datasets/dataset_flakytest/train.json \
    --output_dir=./ \
    --eval_data_file_flaky=./datasets/dataset_flakytest/valid.json \
    --test_data_file_flaky=./datasets/dataset_flakytest/test.json \
    --model_name_or_path=microsoft/unixcoder-base \
    --tokenizer_name=microsoft/unixcoder-base \
    --num_classes 1 \
    --nl_length 128 \
    --code_length 512 \
    --do_train True \
    --train_batch_size 32 \
    --eval_batch_size 32 \
    --train_data_rate_flaky 1.0 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 10 \
    --seed 42 2>&1 | tee ./topConfigs/defect_to_flaky_TOP3.log
